### ISSUE TITLE
java.lang.NullPointerException when qpython uses smsGetMessageIds

### ISSUE THREAD

**Issue by fcgll520** [qpython-android/qpython#1]
import androidhelper
androidhelper.Android().smsGetMessageIds(False, 'inbox').result

then report : java.lang.NullPointerException

please check it why.

**Comment by fcgll521** [comment]
last year, i try it on qpython2, it's fail, and now i try same it on qpython3, it's success

e.g.
import sl4a
droid = sl4a.Android()
msgIDs = droid.smsGetMessageIds(False, 'inbox').result
print(msgIDs)
for id in msgIDs:
    print(droid.smsGetMessageById(id).result)

I have great interesting in this project, hope one day i can enter it.

**Comment by riverfor** [comment]
We had add sms permission in the newest version.

**Comment by jbrepogmailcom** [comment]
Also have this problem, I think it happens when trying to use location services. On other tablet it works, did I forget to install some module?

java.lang.NullPointerException: throw with null exception

Thanks, Jan

**Comment by jbrepogmailcom** [comment]
Fixed. After installation of Qpython3 went to application permissions and turned all ON.
