### ISSUE TITLE
Qpython error code i dont know what to do

### ISSUE THREAD

**Issue by MrJLContreras** [qpython-android/qpython#12]
/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh && exit
iles/bin/qpython-android5.sh && exit           <
Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: no codec search functions registered: can't find encoding
Aborted
134|heroqltespr:/ $

This is what I see when I open the editor. I am a noob and dont know what to do.

**Comment by riverfor** [comment]
Please upgrade to the newest version.
