### ISSUE TITLE
qpython why can't using pillow？

### ISSUE THREAD

**Issue by 1187981465** [qpython-android/qpython#126]
when I test input **from PIL import Image** the editor will be tip the error
can't find the _imaging module , how can I using this Pillow ? thanks everybody help me a little.

**Comment by Marmik2003** [comment]
I also have this problem

**Comment by JustaLiriK** [comment]
My guess : pillow depends on tk wich ins't supported.

**Comment by 1187981465** [comment]
I have give up，I can't do this ,  picture analyse in computer .
