### ISSUE TITLE
Could not obtain the list of AIPY packages.无法获得AIPY包列表。

### ISSUE THREAD

**Issue by w568w** [qpython-android/qpython#138]
(Using QPythonL 2.3.0)  
After installing aipy 1.0.1,I tried to install tensorflow,only to find the page of the list of aipy packages empty.I am sure my net connection is okay.  
 Is it unable to run any machine-learning packages at the moment with AIPY?
  
-----
(使用QPythonL2.3.0)  
安装了aipy1.0.1，但是发现QPython里AIPY库的列表是空的，我确定我的网络状况正常。  
是否目前还不能用aipy运行机器学习相关的库？

**Comment by riverfor** [comment]
Please upgrade your qpython to >=2.4.0.
