### ISSUE TITLE
distributionNotFound pip==9.0.3 when trying to use `pip install` on fresh QPython installation

### ISSUE THREAD

**Issue by caffeinatedMike** [qpython-android/qpython#144]
I've been running into a lot of frustrating issues with the QPython android app for awhile now. Yesterday, I was attempting to install two libraries via `pip`: `requests` & `keyring`. `requests` installed fine, but `keyring` kept failing with some weird error. So, I decided to try starting fresh by uninstalling QPython and reinstalling from the Google Play Store. Now, when I try to use `pip` I get the following Traceback.

```
/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/scripts/pip_console.py" && exit
/qpython/scripts/pip_console.py" && exit <
Input pip commands, ie: pip install {module}
-->pip install requests
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy/files/bin/pip", line 4, in <module>
    from pkg_resources import load_entry_point
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==9.0.3
-->
```

Any idea on how to fix this & successfully install both `requests` & `keyring`?

**Comment by riverfor** [comment]
Did you install the newest QPython ( >=2.4.0 )

Please try to uninstall and reinstall it.

**Comment by caffeinatedMike** [comment]
I did uninstall and reinstall. Version is 2.4.1

Best Regards,

Michael Hill

On Sep 21, 2018 10:17 AM, "River" <notifications@github.com> wrote:

Did you install the newest QPython ( >=2.4.0 )

Please try to uninstall and reinstall it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/qpython-android/qpython/issues/144#issuecomment-423546881>,
or mute the thread

**Comment by riverfor** [comment]
Didn't it work still ?

**Comment by vinish** [comment]
Yes it still not working

**Comment by bdovaz** [comment]
In my case I fix it by switch to python 3 in settings.
