### ISSUE TITLE
newer version do not automatically sort scripts by last modified time?

### ISSUE THREAD

**Issue by KnIfER** [qpython-android/qpython#16]

**Comment by riverfor** [comment]
Which version ?

Have you give a try the newest version (2.0.4) ?

**Comment by pollyfat** [comment]
No, they are not, they sort by name now
But you could list recently modified files by click the **Recent** button as the image below.


![_b9873634-5767-45b7-8fa1-585c4e533110](https://user-images.githubusercontent.com/10812534/30682567-baccb378-9e6f-11e7-8235-069b1b6fec7d.png)
