### ISSUE TITLE
Console not work

### ISSUE THREAD

**Issue by Fernandez-Miguel-A** [qpython-android/qpython#17]
Samsung J3 (2016)
In the console, the button delete and enter not work, to push in this 
Do not delete characters, and do not read the line. The other characters
Work ok (a-z 0-9 Ctrl Shift ... etc).

Copy console:
/data/data/org.qpython.qpy3/files/bin/qpython-android5.sh && exit
/qpython-android5.sh && exit            <
WARNING: linker: zlib.cpython-32m.so: unused DT entry: type 0x6ffffffe arg 0x8a4
WARNING: linker: zlib.cpython-32m.so: unused DT entry: type 0x6fffffff arg 0x1
Python 3.2.2 (default, Jun 18 2015, 19:03:02)
[GCC 4.9 20140827 (prerelease)] on linux-armv7l
Type "help", "copyright", "credits" or "license" for more information.
WARNING: linker: libreadline.so.6: unused DT entry: type 0x1d arg 0x316a
>>>

**Comment by riverfor** [comment]
Newest QPython (not QPython3) has fixed it , do you want to try it ?

**Comment by mbnife** [comment]
I'm useing Qpython3 Pro on an amazon fire HD10 seveth from the amazon application store.

Ver.1.0.2.

It may be an old version. But my mathine cannot use the google application store, and can use only the amazon application store.

What do I do?
