### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by slothonmeth1** [qpython-android/qpython#170]
so I was just trying to connect to my discord bot using my token 
```python
import discord
client = discord.Client()
client.run(MY_TOKEN)
```
and I keep getting `CERTIFICATE_VERIFY_FAILED`
Is there any issues with the SSL implimenting?

**Comment by riverfor** [comment]
It will be fixed in next QPython's update.

I have changed ssl.py
518 _create_default_https_context = _get_https_context_factory()
to
518 _create_default_https_context = _create_unverified_context #_get_https_context_factory()
