### ISSUE TITLE
how to turn on the phone flashlight with qpython ?

### ISSUE THREAD

**Issue by florianpetiot** [qpython-android/qpython#198]
I coded a Python program to make time laps with the Androidhelper library, only I have one last problem: turn on the light of the phone when it is dark

I have searched the documentation of Androidhelper but it seems to me that you can't control the light with it

Do you have a solution? Can you help me?

**Comment by guangrei** [comment]
try use plyer
```python
from plyer import flash

flashlight.on()
flashlight.off()
```
if you got error cant import flash, you have to upgrade it with pip3 install plyer --upgrade

**Comment by florianpetiot** [comment]
Thank you for solving my problem! 

Since September I have already used my program, it was to do a school experiment on the Physarum Polycephalum (Blob). It moves better if it's dark but we put a small light next to it
Here is the result:
https://youtu.be/tNQYsPXUFcY
