### ISSUE TITLE
What's the licence for this code?

### ISSUE THREAD

**Issue by robinpaulson** [qpython-android/qpython#2]
Is it a fork of the original google sl4a, thus Apache 2.0?

**Comment by riverfor** [comment]
YES, it's under the Apache 2.0 license.

On Mon, May 4, 2015 at 8:21 PM, robinpaulson <notifications@github.com>
wrote:

> Is it a fork of the original google sl4a, thus Apache 2.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/QSL4A/issues/2>.
>



-- 
river's showtime, river's game

**Comment by robinpaulson** [comment]
Could you add a "LICENCE" file to the project stating this please?

**Comment by carlsmith** [comment]
@riverfor - You're saying the whole of QPython is available under Apache 2.0? If so, I'll add a proper license to the project repo and make a PR.
