### ISSUE TITLE
qpython3 problem in installing matlpotlib-aipy3

### ISSUE THREAD

**Issue by Toutou-gamer** [qpython-android/qpython#208]
I use qpython3S version 3.0.0. I tried to install some libraries using pip but it requires python version >= 3.8(I have 3.6.6 and I still can't find how to update it). Anyway I used qpypi. I installed numpy, scipy, pandas. But when I tried to install matplotlib they said that I need version 3.6.8 or higher.
I tried many other compilers but nothing wroks for me.

**Comment by guangrei** [comment]
you can get qpython (fork version) with python 3.10 from here https://gitee.com/buddygr/qpython-3c

**Comment by Toutou-gamer** [comment]
can you give me a direct link for the apk file?

**Comment by guangrei** [comment]
heres is the apk https://gitee.com/buddygr/qpython-3c/releases/download/v3.7.1/QPython%203C_3.7.1.apk

**Comment by guangrei** [comment]
you could download apk files from release page https://gitee.com/buddygr/qpython-3c/releases

**Comment by Toutou-gamer** [comment]
thank you!!!! it worked for me!!!!
