### ISSUE TITLE
Can't execute python code and return a result with startActivityForResult (always null)

### ISSUE THREAD

**Issue by bdovaz** [qpython-android/qpython#25]
I'm pulling my hair out trying to communicate from my Android app with QPython to execute some python code and return the result.

I'm trying it with 2.0.0-BETA-2 APK.

Here is documented:

http://www.qpython.org/en/guide_extend.html

And here there is a full project example:

https://github.com/qpython-android/app-call-qpython-api/blob/master/app/src/main/java/org/qpython/sample/MainActivity.java

But my problem is that it doesn't work, it doesn't return any data. On that repository there are issues of other people facing this issue.

Is there a working example doing this? I don't know also what parameters are available. I have been able to discover this two examples:

mBundle.putString("app", "myappid");
mBundle.putString("act", "onPyApi");
mBundle.putString("flag", "onQPyExec");
mBundle.putString("param", ""); 
mBundle.putString("pycode", "");

mBundle.putString("app", "myappid");
mBundle.putString("act", "onPyApi");
mBundle.putString("flag", "SL4A");
mBundle.putString("param", "fileapi");
mBundle.putString("pyfile", path);

**Comment by riverfor** [comment]
Newest version (2.0.4) has fixed this, get it from google play or https://github.com/qpython-android/qpython/releases

**Comment by bdovaz** [comment]
@riverfor are you sure? I have downloaded the sample project your provide that I mentioned on the first message, compiled it and my output is: "onQPyExec: return ()"

The line that prints this:

https://github.com/qpython-android/app-call-qpython-api/blob/master/app/src/main/java/org/qpython/sample/MainActivity.java#L113
