### ISSUE TITLE
Ffplay missing 

### ISSUE THREAD

**Issue by 5perseo** [qpython-android/qpython#27]
Running a  py script for gopro session streaming showed  ffplay missing error.
 Where do i find the missing file?

![screenshot_20170813-095511](https://user-images.githubusercontent.com/30870535/29250879-abde25a6-804a-11e7-9fc6-b847e71b8594.jpg)

**Comment by riverfor** [comment]
It maybe a script which running with universal PC ?
QPython desn't support this way now.

Can you send the GoProStream.py to us, maybe we will consider to support this in the future.

**Comment by 5perseo** [comment]
https://github.com/KonradIT/GoProStream/blob/master/GoProStream.py

That  one . Used on qphyton3 and works well . Command gopro etc but ffplay
command works only on PC.  I m searching for some library or way to letto
it stream on android. By the app ffplay putting the udp chanel, after
GoProStream.py running that initislize the cam, i can stream so i would
just to the Same by the same script....

Il 16 Ago 2017 09:12, "River" <notifications@github.com> ha scritto:
