### ISSUE TITLE
Google Play "Your device is not supported..."

### ISSUE THREAD

**Issue by mark-orion** [qpython-android/qpython#30]
I cannot install QPython via GooglePlay store (your device is not supported).
I tried the install from here: https://play.google.com/store/apps/details?id=org.qpython.qpy&hl=en_GB
However QPython3 seems to be supported and when I download the latest APK from this github page it works as well.
My system: Samsung Galaxy Tab S2 running Lineage OS 14.1 (Android 7.1)

**Comment by riverfor** [comment]
Can you get them from:
https://github.com/qpython-android/qpython/releases
https://github.com/qpython-android/qpython3/releases

**Comment by mark-orion** [comment]
The APKs from github work well. It is only the Play Store that reports that my device is not supported (I never had this happen with any other app before).

**Comment by mark-orion** [comment]
Can you explain why you closed this issue ? The problem is still there.
