### ISSUE TITLE
Tkinter can't be imported

### ISSUE THREAD

**Issue by frodo821** [qpython-android/qpython#31]
I tried importing tkinter, but python raised "ImportError."
> &gt;&gt;&gt; import tkinter
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/python32.zip/tkinter/__init__.py", line 39, in <module>
> ImportError: No module named _tkinter

Can I fix this import?

**Comment by riverfor** [comment]
QPython (QPython3) doesn't support Tkinter yet.

**Comment by frodo821** [comment]
Ok, I understood. Thank you for reply this issue.
