### ISSUE TITLE
Cannot install pip requests

### ISSUE THREAD

**Issue by air3n** [qpython-android/qpython#34]
I always cannot install the pip install requests, always receive error cannot fetch index base url. I already tried to download and put it manually under lib but still canot run py script. Please advise, I not using external memory so the Qpython is in my phone memory. Im using android 5.0
![screenshot_2017-08-25-16-12-05](https://user-images.githubusercontent.com/31342319/29708002-767c3cd4-89b1-11e7-877f-a1e20dc1b853.png)

**Comment by riverfor** [comment]
Newest qpython3 has fixed this issue:

https://github.com/qpython-android/qpython3/releases
