### ISSUE TITLE
可以让脚本注册成一个intent吗？

### ISSUE THREAD

**Issue by bosbyj** [qpython-android/qpython#4]
您好，我想将脚本的界面做成一个intent，想在别的app中通过share文字，至qpython脚本制作的界面，请问可以实现吗？谢谢。

研究了一下，好像有api可以makeIntent，然后startActivity？求教作者大大，再次感谢！

**Comment by riverfor** [comment]
现在的 QPython 有一个share to 的功能，在其他app中选中某些次，然后可以通过分享到的方式分享给某个 qpython脚本，您可以试试。

**Comment by bosbyj** [comment]
谢谢回复。不知到qpython3有没有收录这个功能呢？顺便请告知下具体 share-to 的文档页面。文档部分如果需要人力，我很乐意贡献力量~
祝好
