### ISSUE TITLE
Porting Keras to QPython

### ISSUE THREAD

**Issue by papachristoumarios** [qpython-android/qpython#48]
Hello,

[According to this tweet](https://twitter.com/qpython/status/905817251370213380) you are porting Theano for qpython. It would be a great idea if you ported keras (python framework built on popular ML toolkits) to qpython. That will make prototyping mobile applications that involve neural networks much easier to prototype! 

Thanks in advance

**Comment by riverfor** [comment]
OK, we will try that. : )

**Comment by papachristoumarios** [comment]
It would be great!

**Comment by riverfor** [comment]
To use keras, please install AIPY http://www.aipy.org/ and upgrade qpython to >=2.0.7 .

**Comment by papachristoumarios** [comment]
Guys, you did a great job! :D
