### ISSUE TITLE
QPython 2.0.6 File Button Crashed

### ISSUE THREAD

**Issue by c4dr01d** [qpython-android/qpython#64]
In the version 2.0.6,Push the file button and click the editor's view button,the app crashed.

**Comment by pollyfat** [comment]
Could you please specfied more details?

**Comment by pollyfat** [comment]
Could you please provide more details or upload an image to point the button that causes the crash?

**Comment by c4dr01d** [comment]
Have a crash video，and I send to the Riverc4droid-------- 原始邮件 --------主题：Re: [qpython-android/qpython] QPython 2.0.6 File Button Crashed (#64)发件人：Mae 收件人：qpython-android/qpython 抄送：Anonymous ,Author Could you please specfied more details?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/qpython-android/qpython","title":"qpython-android/qpython","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/qpython-android/qpython"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pollyfat in #64: Could you please specfied more details?"}],"action":{"name":"View Issue","url":"https://github.com/qpython-android/qpython/issues/64#issuecomment-336760638"}}}

**Comment by c4dr01d** [comment]
em，sorry，my email provider says the video size is too big，cannot send to youc4droid-------- 原始邮件 --------主题：Re: [qpython-android/qpython] QPython 2.0.6 File Button Crashed (#64)发件人：Mae 收件人：qpython-android/qpython 抄送：Anonymous ,Author Could you please provide more details or upload an image to point the button that causes the crash?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/qpython-android/qpython","title":"qpython-android/qpython","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/qpython-android/qpython"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pollyfat in #64: Could you please provide more details or upload an image to point the button that causes the crash?"}],"action":{"name":"View Issue","url":"https://github.com/qpython-android/qpython/issues/64#issuecomment-336761206"}}}

**Comment by pollyfat** [comment]
Then could you upload an image and point it out?

**Comment by c4dr01d** [comment]
River solved this issue,and release 2.0.7

**Comment by pollyfat** [comment]
OK, thanks for the feedback.  :)
