### ISSUE TITLE
ImportError: no module named request

### ISSUE THREAD

**Issue by IshakBen** [qpython-android/qpython#78]
whenever i try to run a code i got this error:
ImportError: no module named request

**Comment by britoest** [comment]
Are you trying to use the <b>requests</b> module?

**Comment by britoest** [comment]
If so, try to install the module first...

Open the ready pip script in the script folder, run it, and type <code>pip install requests</code>

**Comment by riverfor** [comment]
Yes, please install requests from QPYPI.

THANKS @britoest

**Comment by IshakBen** [comment]
@britoest @riverfor thanks for the trick but it is not working. i'm trying to run a Bot with this app but everytime it shows me this (no module named request)
i tried what you told me to do but it still not working
