### ISSUE TITLE
wechat page link must point one issue

### ISSUE THREAD

**Issue by ZoomQuiet** [qpython-android/qpython#8]
因为没拿到原创…所以微信文章没留言服务…

那就应该指向一个可以回复意见的空间吧！

要不是自己的 bloh/wiki 页面…含 DISCUS 服务…
但 D服务和谐中…

对每次版本发布建立对应反馈收集 Issue 再分解为对应 bugfix issue 也就自然了~不是？！

**Comment by riverfor** [comment]
欢迎访问 微博 http://weibo.com/qpython 留下宝贵意见
