### ISSUE TITLE
Qpython app crashes in landscape mode

### ISSUE THREAD

**Issue by Fogapod** [qpython-android/qpython#82]
### device
Sony SGP621
android 6.0.1

App crashes after turning device horizontally, crashes immediately after start if launched in landscape mode. Version 2.0.11

edit: added device info

**Comment by riverfor** [comment]
Can you send the /sdcard/qpy_last_err.log to us (support@qpython.org) ? Thank you very much.

**Comment by Fogapod** [comment]
There is no file `/sdcard/qpy_last_err.log`

**Comment by Fogapod** [comment]
Seems fixed in 2.1.1
