### ISSUE TITLE
cant create shortcut on the desktop

### ISSUE THREAD

**Issue by telemaxx** [qpython-android/qpython#87]
in earlier versions i could longpress on a script and create a short cut on the desktop. 
i can't find that function in the latest version. 

that function i miss much. 

thanks for qpython!!!

**Comment by telemaxx** [comment]
now i know how to create shortcuts.
i had some tomatos on my eyes

**Comment by kevenv** [comment]
@telemaxx I can't find how, can you explain how you did?

**Comment by telemaxx** [comment]
![screenshot_20180320-183942](https://user-images.githubusercontent.com/22706487/37672423-36e3d3e2-2c6e-11e8-8236-d3b9319de3f4.jpg)
![screenshot_20180320-184006](https://user-images.githubusercontent.com/22706487/37672438-4468d882-2c6e-11e8-90b3-69c1db5e68ac.png)
longpress on youre script then:
![screenshot_20180320-183958](https://user-images.githubusercontent.com/22706487/37672461-501bb136-2c6e-11e8-8848-3d46eb690988.png)

**Comment by kevenv** [comment]
Wow, that is well hidden! Thank you very much.

**Comment by telemaxx** [comment]
Yes, that icon should be in the group with the other tools. with the text "Programs" below the icon.
