### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by SparkyCola** [qpython-android/qpython#9]
I'd like to add QPython to the FDroid RePo but there's no license mentioned, so it would be hard/impossible to get it through.

**Comment by carlsmith** [comment]
Ditto. Without a licence, this isn't really free software. It's essentially freeware that people are welcome to contribute to. Does QPython use GPL libraries?

**Comment by robinpaulson** [comment]
I asked this question a few months ago. the slightly curt reply was Apache 2: see #2 

It feels rather informal though and I'm reluctant to act upon that response. A "LICENCE" or "COPYING" file would be a big improvement and provide some certainty for downstream, such as f-droid.

**Comment by riverfor** [comment]
Apache Licence 2.0
